version: '2'

services:
  server:
    build: .
    command: server
    ports:
      - "8080:8080"
    volumes:
      - ~/.dockercfg:/root/.dockercfg
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: .env
    user: root
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      EMPIRE_X_SHOW_ATTACHED: 'true'
